//Throw, and Try...Catch...Finally

try {
    addlert("welcome!")         //adddlert as an error
} catch (error) {
    console.log(error.message); 
}
finally{
    console.log(" i am running");
    
}


//plrase, Read the DocumentğŸ”´ğŸ”´ğŸ”´ğŸ”´